# モデル
model = "gpt-5.3-codex"
# 推論
model_reasoning_effort = "medium"
hide_agent_reasoning = true

# Notify（Claude Hooks相当）で音を鳴らす
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

web_search = 'live'
personality = "pragmatic"
